### PR TITLE
update

### PR DESCRIPTION
**Pull request by drifted-mdl**

### CODE REVIEW

**Comment by drifted-mdl** [comment]
@dekdevy im not sure how to solve this conflict, the syntax seems perfectly fine

**Comment by dekdevy** [comment]
@drifted-mdl the conflict is simply that you both added to the files while not updating to the new state (problem when you dont PR often enough) 
basically there is no conflict, you just need to take the contents of both lines.

---->
A
====
B
C
---->

should just be

A
B
C

**Comment by drifted-mdl** [comment]
im not sure about the translations, i was kinda used to doing them solo, but now that yojo contributed im not sure what he translated exactly

**Comment by dekdevy** [comment]
Thanks for the big PR!

**Pull request merged**
