### PR TITLE
Updated ui -> merchant.js with swedish translations. 

### PR DESCRIPTION
**Pull request by Awolize**

### CODE REVIEW

**Comment by drifted-mdl** [comment]
Greetings! Thank you for the translations, they're much appreciated! Are you a native Swedish speaker, or what's your background in terms of the Swedish language?

**Comment by Awolize** [comment]
Hello! Yeah, I am a native Swedish speaker.

**Comment by drifted-mdl** [comment]
Ah, brilliant! What about your English background?

**Comment by Awolize** [comment]
Its my second language, Ive grown up with it. Im currently in university and half of my courses are in English.

**Comment by drifted-mdl** [comment]
You're excellently suited for the job! If you have any inquiries, head over to our Discord server and we'll cater for them there

**Comment by twt-tsunami1** [comment]
Nothing Bad, Nice 👌

**Pull request merged**
