### PR TITLE
Added Turkish translations to Class Names and Descriptions 

### PR DESCRIPTION
**Pull request by Wassupman2**
Turkish translations added to all 4 class names and descrips. :3

### CODE REVIEW

**Comment by Wassupman2** [comment]
Mind ignoring this?

**Comment by zbot473** [comment]
Why?

**Comment by zbot473** [comment]
Oh
You can undo a delete

**Comment by zbot473** [comment]
This is the file, go to classes and click create new file.
```javascript
export default {
  // The class name
  name: {
    en: 'Archer',
    de: 'Jäger',
    se: 'Bågskytt',
    ru: 'Лучник',
    ko: '궁수',
    es: 'Arquero',
    fr: 'Archer',
    pt: 'Arqueiro',
    nl: 'Boogschutter',
    tr: 'Okçu'
  },
  // Class description, visible during character creation
  description: {
    en: 'Archers deal high single target damage and bursty Area of Effect damage. A good archer will always keep their distance and snipe enemies from afar.',
    de: 'Jäger richten großen Schaden bei einzelnen Zielen, und schubweise Flächenschaden an. Ein guter Jäger wird immer auf distanz bleiben.',
    se: 'Bågskytt gör hög skada mot enskilda personer och har även hög Areal skada. En bra bågskytt attackerar alltid från en distans.',
    ru: 'Лучники наносят высокий урон по одиночной цели и взрывной урон по области. Хороший лучник всегда будет держать дистанцию и отстреливать врагов издалека.',
    ko: '궁수는 높은 단일 타겟 데미지와 버스트 에어리어 피해를줍니다. 좋은 궁수는 먼 거리에서 항상 적을 공격합니다.',
    es: 'Los arqueros hacen daño increíble con sus flechas y pueden disparar muchos flechos a una vez con daño explosivo. La estregia mejor es evitar los enemigos y atacar a lo lejos',
    fr: 'Les archers infligent des dégâts élevés sur une cible précise et des dégâts de zone importants. Un bon archer garde toujours ses distances et élimine ses ennemis de loin.',
    pt: 'Arqueiros causam danos altos a um único alvo e danos na Área de Efeito. Um bom arqueiro sempre manterá sua distância e snipe inimigos de longe.',
    nl: 'Boogschutters groot enkel doelschade en barstenschade aan het gebied van het effect toe. Een goede boogschutter zal altijd afstand houden en vijanden uit de verte vernietigen.',
    tr: 'Okçular tek hedeflere yüksek hasar verebilir ve a.o.e hasarı. İyi bir okçu olmanın bir kısmı uzaktan öldürmeyi hatırlamaktır.'
  }
}
```

**Pull request closed without merging**
