### PR TITLE
Hindi Translations

### PR DESCRIPTION
**Pull request by VedantBang**
Hi, 5f5i5v5e5 here. Started Hindi translations.

### CODE REVIEW

**Comment by dekdevy** [comment]
Hey, thank you! 
there are some conflicts , can you resolve them? then this would be good to go!

**Comment by VedantBang** [comment]
Hi! Can I know what the conflicts are?

**Comment by dekdevy** [comment]
it should say so right below this comment "This branch has conflicts that must be resolved"

**Comment by dekdevy** [comment]
Thank you!

**Pull request merged**
