### PR TITLE
Add 'open blacksmith' translations

### PR DESCRIPTION
**Pull request by MaxThePrisberry**

### CODE REVIEW

**Comment by Twttsunami** [comment]
-.-

**Comment by Twttsunami** [comment]
It's closed now

**Comment by dekdevy** [comment]
This text is a placeholder.

**Comment by drifted-mdl** [comment]
The sentence that you translated is clearly not meant to be translated, I'm sure you were fully aware of that. Please don't translate for the sake of translating, especially using Google to bulk-translate in 20 languages. Exactly half of those languages currently have a native speaker available to help out. Please inquire about such things in the discord server.

**Comment by Twttsunami** [comment]
Yeah

**Pull request closed without merging**
